# Generated by Django 2.2.3 on 2019-08-13 09:09

from django.db import migrations

from core.model.audiovisual import AudiovisualRecord
from core.model.searches import Search


def execute(apps, schema_editor):
    audiovisual_records = (
        Search.Builder
        .new_search(AudiovisualRecord)
        .search()
    )
    for audiovisual_record in audiovisual_records:
        audiovisual_record.slug = None
        audiovisual_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190811_0904'),
    ]

    operations = [
        migrations.RunPython(execute)
    ]
