# Generated by Django 2.2.3 on 2019-08-17 17:48

from django.db import migrations

from core.model.audiovisual import DownloadSourceResult
from core.model.searches import Search


def execute(apps, schema_editor):
    results = (
        Search.Builder
        .new_search(DownloadSourceResult)
        .search()
    )
    for result in results:
        result.deleted = False
        result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190813_0909'),
    ]

    operations = [
        migrations.RunPython(execute)
    ]
