# Generated by Django 2.2.3 on 2019-09-02 15:23

from django.db import migrations
from core.model.audiovisual import DownloadSourceResult
from core.model.searches import Search, Condition
from core.tools.strings import VideoQualityInStringDetector


def execute(apps, schema_editor):
    results = (
        Search.Builder
        .new_search(DownloadSourceResult)
        .add_condition(Condition('deleted', Condition.EQUALS, False))
        .search()
    )
    total = len(results)
    n = 0
    for result in results:
        n += 1
        if result.audiovisual_record is None:
            continue
        qd = VideoQualityInStringDetector(result.name)
        if qd.quality != result.quality:
            result.quality = qd.quality
            result.save()
            print(f'[{n}/{total}] Saved {result.name} with new quality ://\t{result.quality}')


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190902_1053'),
    ]

    operations = [
        migrations.RunPython(execute)
    ]
